'use strict';
let atlasTab='districts',atlasSelection='MALL';
const INK6='#eae6d8',GOLD6='#f2d28c',MUTED6='#9cb3bc';
function miniMap(x,y,w,h,z=state.zone,details=false){const m=MAPS[z],sc=Math.min(w/m.w,h/m.h),ox=x+(w-m.w*sc)/2,oy=y+(h-m.h*sc)/2;ctx.drawImage(districtScene(z),ox,oy,m.w*sc,m.h*sc);ctx.fillStyle='#0a24351f';ctx.fillRect(ox,oy,m.w*sc,m.h*sc);const dot=(px,py,c,r)=>{ctx.beginPath();ctx.fillStyle=c;ctx.arc(ox+px*sc,oy+py*sc,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#102832';ctx.lineWidth=1;ctx.stroke();};if(z===state.zone){if(details){npcList().forEach(n=>dot(n.x,n.y,'#8ce3d0',4));WORLD_ENCOUNTERS[z].filter(m=>!state.defeated[mobKey(z,m.id)]).forEach(m=>dot(m.x,m.y,'#ed9987',4));interactables().filter(i=>!i.hidden?.()).forEach(it=>dot(it.x,it.y,it.travel?'#c5dce0':it.id==='rest'?'#9bdda9':'#b9bba1',4));const ob=localObjective();if(ob){const path=findPath(state.player,ob);ctx.strokeStyle='#f9d98ccc';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ox+state.player.x*sc,oy+state.player.y*sc);path.forEach(p=>ctx.lineTo(ox+p.x*sc,oy+p.y*sc));ctx.stroke();dot(ob.x,ob.y,GOLD6,7);}}dot(state.player.x,state.player.y,'#fff7d1',details?6:3);}}
drawWorldHUD=function(){const d=DISTRICTS[state.zone];box(18,18,415,75,'#102b33f2','#526f72');panelText('DISTRICT '+String(Object.keys(DISTRICTS).indexOf(state.zone)+1).padStart(2,'0')+' / 12   •   LV '+d.level+'+',34,30,11,d.color);text(d.name,34,53,20,INK6);box(732,18,530,75,'#102b33f2','#526f72');panelText('NEXT OBJECTIVE',750,29,11,GOLD6);wrapped(getObjective()?.label||'Explore the district',750,49,490,14,INK6,2);box(463,18,230,126,'#15353de8','#607f80');miniMap(469,24,218,114);buttons.push({x:463,y:18,w:230,h:126,label:'Open district atlas',fn:()=>{atlasTab='local';overlay='map';}});drawNavigator();
 box(0,548,W,172,'#102832','#5b7779');state.party.forEach((p,i)=>{const x=18+i*248;box(x,563,236,112,'#18343e','#456269');drawPortrait(p.name,x+9,575,45,56);panelText(p.label,x+65,574,13,ACCENTS[p.name]);panelText('LV '+p.lvl+(p.points?'  +'+p.points+' PT':''),x+65,594,12,GOLD6);panelText('HP '+p.hp+'/'+p.maxHp,x+65,614,11,'#c4dfca');bar(x+65,634,152,6,p.hp,p.maxHp,'#91c5a4');panelText('MP '+p.mp+'/'+p.maxMp,x+10,646,10,'#99c7db');bar(x+111,649,107,5,p.mp,p.maxMp,'#91bfd3');bar(x+10,666,208,3,p.xp,xpRequired(p)||1,GOLD6);buttons.push({x,y:563,w:236,h:112,label:p.label+' progression',fn:()=>modal={type:'talents',selection:i}});});uiButton('P · Progression',1020,563,242,47,()=>modal={type:'talents',selection:0});uiButton('M · District atlas',1020,620,242,47,()=>{atlasTab='districts';atlasSelection=state.zone;overlay='map';});const near=nearestInteraction();panelText(near?'E · '+(near.data.label||near.data.name):'Click to walk  ·  Shift sprint  ·  I supplies  ·  B auto-battle',24,692,12,near?GOLD6:MUTED6);panelText('$'+state.cash+'   •   '+Object.values(state.expedition.missions).filter(s=>s.complete).length+'/6 MISSIONS',1253,692,12,GOLD6,'right');if(near)buttons.push({x:0,y:679,w:720,h:41,label:'Interact',fn:interact});};
drawTitle=function(){drawHeadingBackdrop();ctx.fillStyle='#0b242755';ctx.fillRect(0,0,W,H);box(46,42,722,628,'#102a31f7','#748b83');panelText('DISTRICTS OF DISCOVERY  /  WORK IN PROGRESS',85,79,13,'#a6c8b9');text('CAPITOL',80,137,65,INK6);text('QUEST',80,201,88,GOLD6);wrapped('An expanded adventure through the city above, the tunnels below, and the records in between.',85,321,594,19,'#bbcec9',3);panelText('12 DISTRICTS   •   20 LEVELS   •   9 BOSSES',85,421,13,GOLD6);const opts=getTitleOptions();opts.forEach((o,i)=>uiButton(o.label,85,467+i*55,626,45,()=>{titleSelection=i;o.run();},{active:i===titleSelection,disabled:o.disabled}));['TRUMP','HEGSETH','LUTNICK','RFK'].forEach((n,i)=>{const x=860+(i%2)*220,y=330+Math.floor(i/2)*256;drawShadow(x,y,36,.24);drawActorFrame(ACT.action[n][0],x,y,BATTLE_SCALE[n]*1.02,false);panelText(ROLES[n],x,y+24,12,ACCENTS[n],'center');});panelText('Original sprites · Offline play · Mouse, keyboard & touch',83,643,11,MUTED6);};
modalFrame=function(title,sub=''){ctx.fillStyle='#061820e8';ctx.fillRect(0,0,W,H);box(34,26,1212,668,'#112d37','#617f80');panelText('CAPITOL QUEST / DISTRICTS OF DISCOVERY',58,46,11,MUTED6);text(title,58,77,29,INK6);if(sub)wrapped(sub,58,122,1120,14,MUTED6,2);uiButton('Esc · Close',1090,44,130,39,()=>{overlay=null;modal=null;});};
function travelSelected(){const z=atlasSelection;if(z===state.zone){overlay=null;return;}if(!adv().visited[z]||!isZoneUnlocked(z))return;overlay=null;zoneTransition(z);}
drawMapOverlay=function(){modalFrame('THE DISTRICT ATLAS','Gold routes follow the story. Side districts reward permanent party relics. Rest to recover; revisit any unlocked district.');uiButton('Connections',58,164,183,37,()=>atlasTab='districts',{active:atlasTab==='districts'});uiButton('Local map',251,164,170,37,()=>atlasTab='local',{active:atlasTab==='local'});
 if(atlasTab==='districts'){
 // Layout uses three rows; every node has a defined place in the route network.
 const point=z=>{const p=DISTRICTS[z].at;return {x:p[0],y:p[1]===150||p[1]===160?270:p[1]===360?422:562};};
 for(const [a,b] of LINKS){const p=point(a),q=point(b);ctx.strokeStyle=CORE_ZONES.includes(a)&&CORE_ZONES.includes(b)?'#c6ae74':'#507581';ctx.lineWidth=3;ctx.setLineDash(SIDE_MISSIONS[a]||SIDE_MISSIONS[b]?[7,6]:[]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}ctx.setLineDash([]);
 for(const [z,d] of Object.entries(DISTRICTS)){const p=point(z),visited=adv().visited[z],available=isZoneUnlocked(z),selected=atlasSelection===z,done=SIDE_MISSIONS[z]&&sideState(z).complete;box(p.x-91,p.y-36,182,75,selected?'#34524f':available?'#203e47':'#19323b',selected?GOLD6:visited?'#85b0ad':'#4b666e');panelText((done?'✓ ':z===state.zone?'● ':'')+'LV '+d.level+(SIDE_MISSIONS[z]?' / SIDE':' / STORY'),p.x-77,p.y-26,10,available?d.color:'#617d86');wrapped(d.name,p.x-77,p.y-4,160,12,available?INK6:'#7f959b',2);buttons.push({x:p.x-91,y:p.y-36,w:182,h:75,label:d.name+(visited?' · visited':available?' · discover':' · locked'),fn:()=>atlasSelection=z});}
 const d=DISTRICTS[atlasSelection],visited=adv().visited[atlasSelection];panelText(d.name+' · '+d.tag,60,631,13,d.color);panelText(atlasSelection===state.zone?'You are here':visited?'Fast travel is available':isZoneUnlocked(atlasSelection)?'Enter from a connected district to unlock fast travel':'Progress the main story to unlock this route',60,655,11,MUTED6);uiButton(atlasSelection===state.zone?'Return to world':visited?'Travel here →':'Discover on foot',975,631,239,45,travelSelected,{disabled:atlasSelection!==state.zone&&(!visited||!isZoneUnlocked(atlasSelection)),active:true});
 }else{box(58,218,836,441,'#203b41','#5d7c7e');miniMap(65,224,820,430,state.zone,true);text(DISTRICTS[state.zone].name,924,228,16,INK6);wrapped(DISTRICTS[state.zone].tag,924,266,270,14,MUTED6,2);[['#f2d28c','Objective & route'],['#fff7d1','Your party'],['#8ce3d0','People'],['#ed9987','Visible encounters'],['#9bdda9','Rest points']].forEach(([c,t],i)=>{drawDiamond(934,324+i*39,c,5);panelText(t,952,316+i*39,12,INK6);});wrapped('All paths and obstacles match the world. Follow the gold route to your next objective.',924,542,280,13,MUTED6,4);}
};
const interfaceModalV5=drawModal;
drawModal=function(){if(modal.type==='talents'){modalFrame('PARTY PROGRESSION','Earn XP through battles and exploration. Each level grants a talent point; skills unlock at levels 1, 2, 4, 6 and 9.');state.party.forEach((p,i)=>{const x=58+i*295;box(x,177,281,470,'#193843',modal.selection===i?ACCENTS[p.name]:'#486974');drawPortrait(p.name,x+17,194,54,68);text(p.label,x+86,198,17,ACCENTS[p.name]);panelText(ROLES[p.name],x+86,226,10,MUTED6);panelText('LEVEL '+p.lvl+' / 20',x+18,280,16,GOLD6);panelText(p.points+' TALENT POINT'+(p.points===1?'':'S'),x+18,310,12,p.points?GOLD6:MUTED6);bar(x+18,342,245,8,p.xp,xpRequired(p)||1,GOLD6);panelText(p.lvl>=20?'MAX LEVEL':p.xp+' / '+xpRequired(p)+' XP',x+18,360,11,MUTED6);TALENTS.forEach((t,j)=>uiButton(t.name+' '+p.talents[t.id]+'/'+t.max,x+14,392+j*62,253,55,()=>{modal.selection=i;buyTalent(p,t);},{disabled:!p.points||p.talents[t.id]>=t.max,sub:t.desc,accent:ACCENTS[p.name]}));const next=SKILL_LEVELS.find(l=>l>p.lvl);panelText(next?'NEXT SKILL · LV '+next:'ALL SKILLS UNLOCKED',x+18,590,11,GOLD6);wrapped(next?PARTY_DEFS[p.name].skills[SKILL_LEVELS.indexOf(next)].name:'Master your role. Level cap: 20.',x+18,613,245,11,MUTED6,2);});return;}
 if(modal.type==='automation'){modalFrame('AUTO-BATTLE & PACE','Changes apply immediately. B cycles battle mode; V changes speed; Esc takes manual control.');AUTO_MODES.forEach((name,i)=>uiButton(name,58+i*296,181,280,78,()=>setAutoMode(i),{active:state.settings.autoMode===i,sub:['Choose every action','Heal, buff & exploit weakness','Spend MP for stronger attacks','Basic attacks; heal when needed'][i]}));const rows=[['Battle speed',state.settings.battleSpeed+'×',()=>state.settings.battleSpeed=state.settings.battleSpeed%3+1,'Speeds up actions and enemy turns.'],['Use consumables',state.settings.autoItems?'ON':'OFF',()=>state.settings.autoItems=!state.settings.autoItems,'Allow auto-battle to spend healing and revive items.'],['Use Limit moves',state.settings.autoLimits?'ON':'OFF',()=>state.settings.autoLimits=!state.settings.autoLimits,'Use offensive and healing Limits when helpful.'],['Continue after wins',state.settings.autoContinue?'ON':'OFF',()=>state.settings.autoContinue=!state.settings.autoContinue,'Ordinary wins advance after 1.5s. Level-ups and bosses pause.'],['Difficulty',state.settings.difficulty,()=>{const names=['Story','Standard','Tactical'];state.settings.difficulty=names[(names.indexOf(state.settings.difficulty)+1)%3];},'Applies to the next encounter. Progress rewards stay the same.']];rows.forEach(([label,value,fn,sub],i)=>{panelText(label,66,295+i*70,16,INK6);panelText(sub,66,322+i*70,12,MUTED6);uiButton(value+' ↻',970,286+i*70,232,55,fn,{active:true});});return;}
 if(modal.type==='mission'){const z=modal.zone,m=SIDE_MISSIONS[z],s=sideState(z);modalFrame(m.title,'SIDE MISSION / '+MAPS[z].name+' / LEVEL '+DISTRICTS[z].level+'+');wrapped(m.intro,65,199,1100,23,INK6,4);m.items.forEach((it,i)=>{panelText(s.nodes.includes(i)?'✓':'○',72,358+i*49,20,s.nodes.includes(i)?'#a1d9ad':GOLD6);panelText(it,112,360+i*49,18,INK6);});box(65,531,1139,100,'#294b4e','#7c9991');text(m.relic,86,549,20,GOLD6);panelText(m.reward,86,584,15,INK6);return;}
 if(modal.type==='trials'){modalFrame('THE CHALLENGE BOARD','Six repeatable encounters. Earn XP and cash every run. Three stars: win in four rounds with all heroes standing.');TRIALS.forEach((t,i)=>{const x=58+(i%2)*592,y=181+Math.floor(i/2)*159,stars=state.expedition.trials[i]||0;box(x,y,574,144,'#193a44','#54737b');panelText('LV '+t.level+'   '+('★'.repeat(stars)+'☆'.repeat(3-stars)),x+17,y+13,12,GOLD6);text(t.name,x+17,y+39,19,INK6);wrapped(t.desc,x+17,y+72,530,12,MUTED6,2);uiButton('Challenge →',x+341,y+101,215,33,()=>beginTrial(i));panelText('+'+t.xp+' XP · $'+t.gold,x+17,y+112,11,'#abcab3');});return;}
 if(modal.type==='newgame'){modalFrame('START A NEW GAME?','Your autosave will be replaced after the introduction. Export it first if you want to keep a separate copy.');wrapped('Your earlier save slot remains available. Choose Continue to migrate it into the new districts.',65,235,1100,23,INK6,4);uiButton('Keep current game',65,468,544,70,()=>modal=null,{active:modal.selection===0});uiButton('Begin new game',641,468,544,70,()=>{modal=null;startNewGame();},{active:modal.selection===1});return;}
 interfaceModalV5();
};
const modalKeysV5=modalInput;
modalInput=function(k){if(['talents','automation','trials','mission'].includes(modal.type)){if(k==='escape'||k==='p'&&modal.type==='talents'||k==='b'&&modal.type==='automation'){modal=null;saveGame(false);return;}if(modal.type==='talents'){if(['arrowleft','a'].includes(k))modal.selection=(modal.selection+3)%4;if(['arrowright','d'].includes(k))modal.selection=(modal.selection+1)%4;if(['1','2','3'].includes(k))buyTalent(state.party[modal.selection],TALENTS[+k-1]);}if(modal.type==='automation'){if(['1','2','3','4'].includes(k))setAutoMode(+k-1);if(k==='v')state.settings.battleSpeed=state.settings.battleSpeed%3+1;}if(modal.type==='trials'){if(['arrowup','w','arrowleft','a'].includes(k))modal.selection=(modal.selection+5)%6;if(['arrowdown','s','arrowright','d'].includes(k))modal.selection=(modal.selection+1)%6;if(['enter','e',' '].includes(k))beginTrial(modal.selection);}return;}modalKeysV5(k);};
const menuKeys6=handleInput;
handleInput=function(k){if(!modal&&overlay==='map'){if(['m','escape'].includes(k)){overlay=null;return;}if(k==='tab'){atlasTab=atlasTab==='local'?'districts':'local';return;}if(atlasTab==='districts'){const list=Object.keys(DISTRICTS),i=list.indexOf(atlasSelection);if(['arrowleft','a','arrowup','w'].includes(k))atlasSelection=list[(i+11)%12];if(['arrowright','d','arrowdown','s'].includes(k))atlasSelection=list[(i+1)%12];if(['enter','e',' '].includes(k))travelSelected();}return;}menuKeys6(k);};
pauseOptions=function(){return [{label:'Resume',run:()=>mode='world'},{label:'Save game',run:()=>saveGame()},{label:'Auto-battle & difficulty',run:()=>{mode='world';modal={type:'automation',selection:0};}},{label:'Party progression',run:()=>{mode='world';modal={type:'talents',selection:0};}},{label:'Sound: '+(state.settings.sound?'ON':'OFF'),run:()=>{state.settings.sound=!state.settings.sound;if(!state.settings.sound)audioCtx?.suspend();else audioCtx?.resume();}},{label:'Screen shake: '+(state.settings.shake?'ON':'OFF'),run:()=>state.settings.shake=!state.settings.shake},{label:'Return to title',run:()=>{saveGame(false);mode='title';titleSelection=0;}}];};
drawEnemySprite=function(name,x,y,scale=1,flip=false,alpha=1){drawFacingEnemy(name,x,y,scale,flip?'right':'left',alpha);};
const actionPanelV5=drawBattleMenuPanel;
drawBattleMenuPanel=function(){const p=currentActor();if(battle.phase==='skills'){const list=skillsFor(p);list.forEach((s,i)=>uiButton(s.name+(s.limit?' ★':' · '+s.cost),748+i%2*256,509+Math.floor(i/2)*51,244,45,()=>{battle.subIndex=i;chooseSkill(s);},{active:battle.subIndex===i,disabled:!s.limit&&p.mp<s.cost,sub:'',accent:ACCENTS[p.name]}));const s=list[battle.subIndex];wrapped((s?.limit?'LIMIT':(s?.cost||0)+' MP')+' · '+(s?.desc||''),748,672,488,11,MUTED6,2);return;}actionPanelV5();};
function resultHUD(){const r=battle.result;box(0,470,W,250,'#102c36','#78918a');text(r.multi?'SECURITY WAVE '+(battle.reward.wave+1)+' / 3 CLEARED':'ENCOUNTER CLEARED',23,486,21,GOLD6);panelText('+'+r.xp+' XP / HERO    $'+r.gold+'    '+r.rounds+' ROUNDS    '+r.breaks+' BREAKS',1258,489,12,INK6,'right');state.party.forEach((p,i)=>{const x=18+i*312,gain=r.gains.find(g=>g.name===p.name);box(x,524,300,130,gain?'#2d4a45':'#193944',gain?GOLD6:'#4e7078');drawPortrait(p.name,x+12,539,44,55);panelText(p.label,x+67,539,14,ACCENTS[p.name]);panelText(gain?'LEVEL UP '+gain.from+' → '+gain.to:'LEVEL '+p.lvl,x+67,565,15,gain?GOLD6:INK6);panelText(gain?'+'+(gain.to-gain.from)+' talent point · HP / MP full':p.lvl===20?'Level cap reached':p.xp+' / '+xpRequired(p)+' XP',x+14,605,11,MUTED6);bar(x+14,635,271,6,p.xp,xpRequired(p)||1,GOLD6);});panelText(r.relic?'RELIC UNLOCKED · '+r.relic:r.multi?'Next wave restores 18% HP and 15% MP.':'Victory recovery: 12% HP / 10% MP. Open P in the world to spend points.',23,682,12,r.relic?GOLD6:MUTED6);uiButton(r.multi?'Next wave →':'Continue →',1062,671,200,36,()=>finishBattle(true,false),{active:true});}
const battleHUDV5=drawBattleHUD;
drawBattleHUD=function(){if(battle.phase==='victory')resultHUD();else drawPartyBattle6();box(15,12,1250,60,'#102b35','#64838a');panelText('ROUND '+battle.round,31,26,12,GOLD6);wrapped(battle.message,139,25,1102,15,INK6,2);uiButton('B · '+AUTO_MODES[state.settings.autoMode],18,82,216,39,cycleAuto,{active:state.settings.autoMode>0});uiButton('V · '+state.settings.battleSpeed+'×',246,82,114,39,()=>state.settings.battleSpeed=state.settings.battleSpeed%3+1);uiButton('Options',372,82,140,39,()=>modal={type:'automation',selection:0});if(state.settings.autoMode)panelText('Esc · manual control',18,131,11,GOLD6);};
const questV5=drawQuestOverlay;
drawQuestOverlay=function(){questV5();box(811,568,405,85,'#173b43','#567983');panelText('Side missions '+Object.values(state.expedition.missions).filter(m=>m.complete).length+'/6  ·  Caches '+Object.keys(adv().chests).length+'/12',828,582,12,GOLD6);uiButton('Open district atlas →',828,608,369,34,()=>{overlay='map';atlasTab='districts';});};
drawControlsOverlay=function(){modalFrame('HOW TO PLAY','A complete story, six side missions, six repeatable trials, and progression through level 20.');const rows=[['MOVE','WASD / arrows, Shift to sprint, or click a destination.'],['INTERACT','E / Enter near a person or marker. Click to walk to it.'],['MAP','M opens the connected atlas. Tab switches to the local map.'],['PROGRESSION','P opens talents. Spend 1 / 2 / 3 on the selected hero.'],['MENUS','I supplies, Q journal, B auto-battle options, Esc pause.'],['BATTLE','Read enemy intent. Two weakness hits cause BREAK; bosses then resist breaks for one round.'],['RECOVER','Basic attacks restore 5 MP; Defend restores 10 MP.'],['AUTO-BATTLE','B cycles modes; V changes speed; Esc takes control.'],['EXPLORATION','Side missions unlock relics. The Mall board offers repeatable trials.'],['SAVE','Rest, F5, and autosave. Export / Import carries saves between browsers.']];rows.forEach(([a,b],i)=>{panelText(a,65,184+i*42,13,GOLD6);panelText(b,245,184+i*42,13,INK6);});panelText('Original sprite set. This game is fictional satire. Landscape is best on small screens.',65,641,11,MUTED6);};
// Keep save and UI state portable, and reset transient navigation on load.
const loadGameV6=loadGame;
loadGame=function(show=true){walkPath=[];walkTarget=null;modal=null;loadGameV6(show);if(mode==='world')encounterGrace=3;};
const newGameV6=startNewGame;
startNewGame=function(){modal=null;walkPath=[];walkTarget=null;newGameV6();cutscene.pages[3].text='Meet the rally witness on the Mall. Click to walk, or use WASD. The district atlas connects twelve areas; the garden offers your first side mission. Battles earn XP. P opens talents, and B opens auto-battle options.';};
Object.assign(window.__CQ__,{DISTRICTS,SIDE_MISSIONS,LINKS,LOCATIONS,TRIALS,SKILL_LEVELS,WALK_FRAMES6,ENEMY_FACING6,findPath,xpRequired,grantPartyXP,buyTalent,chooseAutoAction,beginTrial,setAutoMode,getObjective:()=>getObjective(),interactables:()=>interactables(),worldSolids:z=>worldSolids(z),startNewGame:()=>startNewGame(),freshState:()=>freshState(),startBattle:(...a)=>startBattle(...a),zoneTransition:(...a)=>zoneTransition(...a),finishBattle:(...a)=>finishBattle(...a),winBattle:()=>winBattle(),retreat:()=>retreat(),retryBattle:()=>retryBattle(),resolvePlayerAction:a=>resolvePlayerAction(a),resolveEnemyAction:e=>resolveEnemyAction(e),skillsFor:p=>skillsFor(p),chooseSkill:s=>chooseSkill(s),battleTargets:()=>battleTargets(),saveGame:(...a)=>saveGame(...a),loadGame:(...a)=>loadGame(...a),draw:()=>draw(),update:dt=>update(dt),setModal:m=>modal=m,setOverlay:o=>overlay=o,sideState,makeEnemy,refreshIntents,restoreParty,mergeState});
function drawPartyBattle6(){box(0,470,W,250,'#102832','#527078');panelText('PARTY',23,486,12,MUTED6);panelText('ACTION',752,486,12,MUTED6);state.party.forEach((p,i)=>{const x=18,y=509+i*47,active=currentActor()===p&&['input','skills','items','target','analyze'].includes(battle.phase);box(x,y,704,43,active?'#2e474a':'#17353f',active?ACCENTS[p.name]:'#3c5c66');drawPortrait(p.name,23,y+4,28,35);panelText(p.label,61,y+5,13,p.alive?ACCENTS[p.name]:'#7b8e91');panelText('LV '+p.lvl,61,y+24,9,MUTED6);panelText('HP '+p.hp+'/'+p.maxHp,187,y+5,11,'#c8dfd1');bar(187,y+27,145,6,p.hp,p.maxHp,'#96c9a7');panelText('MP '+p.mp+'/'+p.maxMp,352,y+5,11,'#a5c8da');bar(352,y+27,113,6,p.mp,p.maxMp,'#88b5d0');panelText(p.limit===100?'LIMIT READY':'LIMIT '+p.limit+'%',489,y+5,11,'#ccaccc');bar(489,y+27,108,6,p.limit,100,'#c196bd');wrapped(statusText(p),617,y+6,96,9,'#b3ccda',2);});drawBattleMenuPanel();}
