'use strict';
// Capitol Quest: Complete Record — gameplay and presentation layer.
// All character, portrait, landmark, tile and effect art comes from the supplied atlas.
const BASIC_NAMES={TRUMP:'Power Punch',HEGSETH:'Rifle Shot',LUTNICK:'Cash Toss',RFK:'Signal Bolt'};
const ROLES={TRUMP:'VANGUARD',HEGSETH:'MARKSMAN',LUTNICK:'BROKER',RFK:'MEDIC'};
const ACCENTS={TRUMP:'#f8ce76',HEGSETH:'#99d4af',LUTNICK:'#8fc9ff',RFK:'#b7a0f4'};
const extraAtlas=new Image();extraAtlas.src='assets/extras.png';
let buttons=[],pointer={x:-1,y:-1},modal=null,supplyIndex=0,allyIndex=0;
const TILE={grass:[1447,331,27,23],paving:[1279,51,39,34],water:[1279,127,43,37],floor:[1422,394,36,17],carpet:[1194,404,31,39],shelf:[1473,429,52,56],column:[1263,405,37,53],door:[1421,421,44,53],desk:[1464,501,59,37]};
const REST={MALL:{x:1720,y:705},GROUNDS:{x:470,y:1165},ROTUNDA:{x:470,y:915},ARCHIVE:{x:450,y:1115},PRESS:{x:470,y:1040},HEARING:{x:1050,y:930}};
const BREAKERS=[{x:400,y:720,label:'01 · WEST'},{x:1220,y:710,label:'02 · EAST'},{x:1740,y:450,label:'03 · NORTH'}];
const CATALOG=[{x:445,y:350,label:'Intake · 04'},{x:1065,y:400,label:'Transfer · 17'},{x:1380,y:680,label:'Release · 29'}];
const ROOM_NAMES={MALL:'01 / THE RALLY',GROUNDS:'02 / SERVICE ROUTE',ROTUNDA:'03 / THE CHECKPOINT',ARCHIVE:'04 / PAPER TRAIL',PRESS:'05 / DEAD AIR',HEARING:'06 / ON THE RECORD'};
function adv(){return state.adventure;}
function panelText(s,x,y,size=16,color='#dce5f3',align='left'){text(s,x,y,size,color,align,500);}
function box(x,y,w,h,fill='#101d30',stroke='#34465b'){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,w-1,h-1);}
function pill(s,x,y,color='#f8ce76'){const w=String(s).length*8+20;box(x,y,w,23,'#12263a',color);panelText(s,x+10,y+4,12,color);}
function uiButton(label,x,y,w,h,fn,{active=false,disabled=false,sub='',accent='#f8ce76'}={}){
  const hot=pointer.x>=x&&pointer.x<x+w&&pointer.y>=y&&pointer.y<y+h;
  box(x,y,w,h,active?'#29364a':hot&&!disabled?'#223148':'#142238',active?accent:'#3b4b60');
  if(active){ctx.fillStyle=accent;ctx.fillRect(x,y,4,h);}
  panelText(label,x+15,y+(sub?11:(h-17)/2),16,disabled?'#758295':active?accent:'#eef3fb');
  if(sub)panelText(sub,x+15,y+36,12,disabled?'#758295':'#a6b7ce');
  buttons.push({x,y,w,h,fn,disabled,label});
}
function wrapped(s,x,y,w,size=16,color='#b8c7da',lines=3){return wrap(s,x,y,w,size*1.5,size,color,lines);}
function rule(x,y,w){ctx.fillStyle='#304056';ctx.fillRect(x,y,w,1);}
function drawExtra(key,x,y,w,h,frame=0){const q=EXTRA[key];const r=Array.isArray(q?.[0])?q[frame]:q;if(!r||!extraAtlas.complete||!extraAtlas.naturalWidth)return;ctx.drawImage(extraAtlas,...r,Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
drawItem=function(key,x,y,size=38){const r=EXTRA[key];if(!r)return;const sc=size/Math.max(r[2],r[3]);drawExtra(key,x-r[2]*sc/2,y-r[3]*sc/2,r[2]*sc,r[3]*sc);};
// Distances along the actual path, independent of frames per second.
resetTrail=function(){trail=[{x:state.player.x,y:state.player.y,dir:state.player.dir,frame:0}];lastTrailPoint={...trail[0]};trailDistance=0;};
function recordTrail(){const p=state.player;trail.unshift({x:p.x,y:p.y,dir:p.dir,frame:p.frame});let d=0,end=trail.length;for(let i=1;i<trail.length;i++){d+=dist(trail[i-1],trail[i]);if(d>240){end=i+1;break;}}trail.length=end;lastTrailPoint={...trail[0]};}
function followerAt(distance){let pts=[{...state.player},...trail],remaining=distance;for(let i=1;i<pts.length;i++){const d=dist(pts[i-1],pts[i]);if(d>=remaining&&d>0){const t=remaining/d;return {x:lerp(pts[i-1].x,pts[i].x,t),y:lerp(pts[i-1].y,pts[i].y,t),dir:pts[i-1].dir,frame:state.player.frame};}remaining-=d;}return {...pts[pts.length-1],frame:0};}
function recoverPlayerPosition(){const p=state.player,m=currentMap();p.x=clamp(Number(p.x)||m.spawn.x,110,m.w-110);p.y=clamp(Number(p.y)||m.spawn.y,120,m.h-120);if(!collides(p.x,p.y))return;for(let r=24;r<Math.max(m.w,m.h);r+=24)for(let a=0;a<Math.PI*2;a+=Math.PI/16){const x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;if(x>110&&y>120&&x<m.w-110&&y<m.h-100&&!collides(x,y)){p.x=x;p.y=y;return;}}}
walkMeta=function(name,dir,frame){let seq;if(dir==='up')seq=name==='TRUMP'||name==='HEGSETH'?[4,5,4,5]:[3,4,5,4];else if(dir==='down')seq=[0,1,2,1];else seq=name==='TRUMP'?[2,3,2,3]:[2,2,2,2];return ACT.walk[name][seq[frame%4]];};
drawPartySprite=function(name,dir,frame,x,y,scale=1,alpha=1){const base={TRUMP:77,HEGSETH:84,LUTNICK:81,RFK:97}[name],sc=72/base*scale;const meta=walkMeta(name,dir,frame);drawActorFrame(meta,x,y,sc,dir==='left',alpha);};
drawWorldEntities=function(){const actors=npcList().map(n=>({y:n.y,draw:()=>drawNPC(n)}));for(const mob of WORLD_ENCOUNTERS[state.zone]||[]){if(state.defeated[mobKey(state.zone,mob.id)])continue;const mm=worldMobMotion[mobKey(state.zone,mob.id)]||mob;actors.push({y:mm.y,draw:()=>drawMob(mob,mm)});}['HEGSETH','LUTNICK','RFK'].forEach((name,i)=>{const tp=followerAt(46*(i+1));if(dist(tp,state.player)<12)return;actors.push({y:tp.y,draw:()=>{drawShadow(tp.x,tp.y,21,.2);drawPartySprite(name,tp.dir,tp.frame,tp.x,tp.y,1,.98);}});});actors.push({y:state.player.y,draw:()=>{drawShadow(state.player.x,state.player.y,23);drawPartySprite('TRUMP',state.player.dir,state.player.frame,state.player.x,state.player.y,1);}});actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());};
drawNPC=function(n){drawShadow(n.x,n.y,22,.2);if(ACT.npc[n.sprite])drawNpcSprite(n.sprite,n.x,n.y,1.05);else drawEnemySprite(n.sprite,n.x,n.y,.66);if(dist(n,state.player)<200){const w=n.name.length*8+20;box(n.x-w/2,n.y-101,w,25,'#0b172bdd','#52718b');panelText(n.name,n.x,n.y-96,13,'#eff5ff','center');}};
drawMob=function(m,mm){drawShadow(mm.x,mm.y,22,.22);drawEnemySprite(m.type,mm.x,mm.y,.66,mm.dir==='right');drawDiamond(mm.x,mm.y-91,encounterGrace>0?'#8994a2':'#fb9285',6);};
const baseUpdateWorld=updateWorld;
updateWorld=function(dt){state.player.speed=keys.has('shift')?310:205;baseUpdateWorld(dt);};
const baseMerge=mergeState;
mergeState=function(dst,src){baseMerge(dst,src);const defaults=freshState().adventure;dst.adventure={...defaults,...src.adventure,upgrades:{...defaults.upgrades,...src.adventure?.upgrades},chests:{...src.adventure?.chests},visited:{MALL:true,...src.adventure?.visited}};dst.party=freshState().party.map((p,i)=>{const saved=src.party?.find(q=>q.name===p.name)||src.party?.[i]||{};return {...p,...saved,status:{},alive:(saved.hp??p.hp)>0};});};
const baseTransition=zoneTransition;
zoneTransition=function(zone,spawn){adv().visited[zone]=true;baseTransition(zone,spawn);};
// The buildings use their original atlas tiles. The floor patterns are cached, never stretched scenery.
function tileRect(key,x,y,w,h,size=64){const r=TILE[key];if(!atlasReady||!r)return;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();for(let yy=y;yy<y+h;yy+=size)for(let xx=x;xx<x+w;xx+=size)drawImageRect(r,xx,yy,size,size);ctx.restore();}
drawOutdoorBase=function(m){tileRect('grass',0,0,m.w,m.h,64);tileRect('paving',0,655,m.w,170,64);tileRect('paving',m.w*.46,90,160,m.h-180,64);tileRect('paving',190,895,m.w-370,340,64);if(state.zone==='MALL'){box(638,443,784,169,'#b7beb8','#dae0d2');tileRect('water',650,455,760,145,64);for(let i=0;i<8;i++){ctx.fillStyle='#d8f2ff44';ctx.fillRect(675+i*89,479+(i%3)*37,37,2);}}drawTreeLines(m);};
drawInteriorBase=function(m,theme){tileRect('floor',0,0,m.w,m.h,64);ctx.fillStyle=theme==='archive'?'#49332533':theme==='press'?'#17366355':'#171b2d22';ctx.fillRect(0,0,m.w,m.h);tileRect('carpet',0,80,m.w,72,64);};
drawColumn=function(x,y){drawImageRect(TILE.column,x,y,75,150);};
drawShelf=function(x,y,h){tileRect('shelf',x,y,210,h,105);};
drawDesk=function(x,y,w,h){tileRect('desk',x,y,w,h,100);};
drawReadingTable=function(x,y){drawDesk(x,y,510,115);};
drawHedges=function(x,y,w,h){tileRect('grass',x,y,w,h,48);for(let xx=x;xx<x+w-45;xx+=78)drawLandmark('TREE',xx,y-25,1.6);};
const baseDrawObjects=drawMapObjects;
drawMapObjects=function(z){baseDrawObjects(z);const rest=REST[z];drawItem('MEDKIT',rest.x,rest.y-16,32);pill('REST',rest.x-26,rest.y+7,'#95deb8');if(z==='GROUNDS')BREAKERS.forEach((b,i)=>{pill(b.label,b.x-48,b.y-125,adv().breakers.includes(i)?'#95deb8':'#f8ce76');});if(z==='ARCHIVE')CATALOG.forEach((c,i)=>{if(!adv().catalog.includes(i)){drawItem('FILE',c.x,c.y-25,36);}});};
const baseInteractables=interactables;
interactables=function(){const arr=baseInteractables(),a=adv(),z=state.zone;const rest=REST[z];arr.push({id:'rest',...rest,label:'Rest & save',run:()=>{state.party.forEach(p=>{p.hp=p.maxHp;p.mp=p.maxMp;p.alive=true;p.status={};});saveGame(false);notify('HP & MP RESTORED · PROGRESS SAVED');sfx('heal');}});
 if(z==='MALL'){arr.push({id:'upgrade',x:600,y:1190,label:'Party training',icon:'FILE',run:()=>{modal={type:'upgrade',selection:0};}});arr.push({id:'tutorial',x:750,y:1160,label:'Practice encounter',run:()=>startBattle([{type:'PROTESTER',level:2}],{gold:0,practice:true,label:'PRACTICE · Learn to break an enemy'})});}
 if(z==='GROUNDS'){BREAKERS.forEach((b,i)=>arr.push({id:'breaker'+i,...b,label:'Relay switch '+(i+1),run:()=>{if(a.breakers.includes(i)){notify('SWITCH ALREADY POWERED');return;}a.breakers.push(i);notify(`RELAY POWER ${a.breakers.length}/3`);sfx('save');saveGame(false);}}));const cart=arr.find(i=>i.id==='megaphone'),run=cart.run;cart.run=()=>{if(a.breakers.length<3){notify('RESTORE THE THREE RELAY SWITCHES · '+a.breakers.length+'/3');return;}run();saveGame(false);};}
 if(z==='ARCHIVE'){CATALOG.forEach((c,i)=>arr.push({id:'catalog'+i,...c,hidden:()=>a.catalog.includes(i),label:c.label,run:()=>{a.catalog.push(i);notify('CATALOG CARD FOUND · '+c.label.toUpperCase());saveGame(false);}}));const ledger=arr.find(i=>i.id==='ledger'),run=ledger.run;ledger.run=()=>{if(!a.archiveOpen){modal={type:'archive',selection:0};return;}run();saveGame(false);};}
 if(z==='PRESS'){arr.push({id:'channel',x:1215,y:710,label:'Tune relay channel',icon:'USB',run:()=>{modal={type:'channel',selection:0};}});const fixer=arr.find(i=>i.id==='fixer'),run=fixer.run;fixer.run=()=>{if(!a.channelOpen){notify('THE CONTROL ROOM IS JAMMED · TUNE THE RELAY FIRST');return;}run();};}
 if(z==='HEARING'){[{x:415,y:480,label:'Submit source originals'},{x:1030,y:480,label:'Submit verification card'}].forEach((p,i)=>arr.push({id:'brief'+i,...p,hidden:()=>a.briefs.includes(i),icon:'DOC',run:()=>{if(!state.flags.factChecked){notify('GET FACT CHECKER SIGN-OFF FIRST');return;}a.briefs.push(i);notify('HEARING EVIDENCE FILED · '+a.briefs.length+'/2');saveGame(false);}}));const chair=arr.find(i=>i.id==='chair'),run=chair.run;chair.run=()=>{if(a.briefs.length<2){notify('FILE BOTH EVIDENCE PACKAGES AT THE SIDE DESKS');return;}run();};}
 const caches={MALL:{x:190,y:570},GROUNDS:{x:1790,y:280},ROTUNDA:{x:1140,y:410},ARCHIVE:{x:1100,y:860},PRESS:{x:1330,y:520},HEARING:{x:200,y:880}};
 if(caches[z])arr.push({id:'cache',...caches[z],icon:'FILE',label:'Supply cache',hidden:()=>a.chests[z],run:()=>{a.chests[z]=true;state.cash+=65;state.inventory.SERUM++;state.inventory.MEDKIT++;notify('CACHE · +65 CASH · SERUM · MEDKIT');saveGame(false);}});
 return arr;};
const baseObjective=getObjective;
getObjective=function(){const a=adv(),z=state.zone;if(state.mainStage===2&&a.breakers.length<3){const i=BREAKERS.findIndex((_,i)=>!a.breakers.includes(i));return {...BREAKERS[i],zone:'GROUNDS',label:`Restore relay switches (${a.breakers.length}/3)`};}if(state.mainStage===4&&!a.archiveOpen){if(a.catalog.length<3){const i=CATALOG.findIndex((_,i)=>!a.catalog.includes(i));return {...CATALOG[i],zone:'ARCHIVE',label:`Collect catalog cards (${a.catalog.length}/3)`};}return {zone:'ARCHIVE',x:950,y:860,label:'Open the ledger vault · Intake → Transfer → Release'};}if(state.mainStage===5&&!state.flags.fixer&&!a.channelOpen)return {zone:'PRESS',x:1215,y:710,label:'Tune the relay · channel 2 / 4 / 1'};if(state.mainStage===7&&a.briefs.length<2)return {zone:'HEARING',x:a.briefs.includes(0)?1030:415,y:480,label:`File the hearing evidence (${a.briefs.length}/2)`};return baseObjective();};
function battleTargets(){if(battle.pending?.targetType==='enemy')return aliveEnemies();if(battle.pending?.kind==='item'&&ITEMS[battle.pending.item]?.revive)return state.party;return aliveParty();}
function weakness(e){return ['Armored','Guard','Tech'].some(t=>e.trait.includes(t))?'magic':e.trait.includes('Media')||e.trait.includes('Quick')?'hybrid':'physical';}
function attackType(a){if(a.kind==='basic')return a.actor.name==='RFK'?'magic':a.actor.name==='LUTNICK'?'hybrid':'physical';return a.skill?.kind.replace('All','')||'none';}
const baseResolvePlayer=resolvePlayerAction;
resolvePlayerAction=function(a){const enemies=(a.target?[a.target]:a.targets||[]).filter(t=>battle.enemies.includes(t));const snapshots=enemies.map(t=>t.hp);baseResolvePlayer(a);enemies.forEach((e,i)=>{if(e.hp>=snapshots[i]||e.hp<=0)return;if(attackType(a)===weakness(e)&&!e.resolveTurns){e.breakPoints=(e.breakPoints||0)+1;addFloater(e,'WEAK','#f8ce76');if(e.breakPoints>=2){e.breakPoints=0;e.broken=true;addStatus(e,'vulnerable',2);battle.message+=' BREAK! Enemy loses its next action.';addFloater(e,'BREAK!','#84e4fa');}}});};
function planIntent(e){if(e.broken)return {kind:'broken',label:'BROKEN · skips turn',power:0};const n=battle.round;if(e.boss&&n%3===0)return {kind:'sweep',label:'CHARGING · party hit',power:.95};if(e.hp/e.maxHp<.4&&['nurse','senior'].includes(e.ai))return {kind:'heal',label:'Recover HP',power:1};if(n%3===2&&['veteran','union','sentinel'].includes(e.ai))return {kind:'guard',label:'Brace · armor up',power:1};return {kind:['teacher','journalist','scientist','fixer','chair','activist'].includes(e.ai)?'magic':'physical',label:['teacher','journalist','scientist','fixer','chair','activist'].includes(e.ai)?'Signal strike':'Physical strike',power:e.boss?1.25:1};}
function refreshIntents(){battle.enemies.forEach(e=>{e.intent=planIntent(e);});}
const baseStartBattle=startBattle;
startBattle=function(specs,reward={}){baseStartBattle(specs,reward);if(!battle)return;refreshIntents();battle.message=reward.practice?'PRACTICE · Hit a weakness twice to BREAK an enemy. Defend against charged attacks.':`${reward.label||'ENCOUNTER'} · Read enemy intentions before choosing.`;battle.autoTimer=0;};
const baseStartEnemy=startEnemyAction;
startEnemyAction=function(){const round=battle.round;baseStartEnemy();if(battle&&battle.round!==round)refreshIntents();};
resolveEnemyAction=function(e){if(e.broken){e.broken=false;e.intent=planIntent(e);battle.message=`${e.name} is broken and loses its turn.`;return;}const move=e.intent||planIntent(e),living=aliveParty();if(!living.length)return loseBattle();battle.message=`${e.name}: ${move.label}.`;if(move.kind==='guard'){e.guard=true;addStatus(e,'defUp',2);addFx('buff',enemyPos(e).x,enemyPos(e).y-60);return;}if(move.kind==='heal'){const n=Math.min(e.maxHp-e.hp,Math.round(e.maxHp*.2));e.hp+=n;addFloater(e,'+'+n,'#95deb8');return;}const targets=move.kind==='sweep'?living:[choice(living)];for(const t of targets){const magic=move.kind==='magic'||(move.kind==='sweep'&&['fixer','chair'].includes(e.ai));applyDamage(t,magic?damageMagic(e,t,move.power):damagePhysical(e,t,move.power));addFx(magic?'magic':'hit',partyPos(t).x,partyPos(t).y-65);}if(!aliveParty().length)loseBattle();};
// Results use game time and explicit confirmation, never stale wall-clock callbacks.
winBattle=function(){if(!battle||battle.phase==='victory')return;const r=battle.reward;const xp=r.practice?0:r.boss?320:115,gold=r.practice?0:r.gold??50;state.cash+=gold;if(!r.practice){adv().battles++;state.party.forEach(p=>{p.xp+=xp;p.limit=Math.min(100,p.limit+22);levelCheck(p);});}if(r.worldMob)state.defeated[r.worldMob]=true;if(r.boss==='SENTINEL'){state.flags.sentinel=true;setStage(4);}if(r.boss==='FIXER')state.flags.fixer=true;if(r.boss==='CHAIR'){state.flags.chair=true;setStage(8);}battle.phase='victory';battle.result={xp,gold};battle.message=r.practice?'PRACTICE COMPLETE · No supplies or health lost.':`VICTORY · +${gold} cash · +${xp} XP to each party member`;sfx('victory');};
loseBattle=function(){if(!battle)return;battle.phase='defeat';battle.message='FALL BACK · Retry this encounter or recover at the nearest rest point.';};
function retreat(){state.party.forEach(p=>{p.hp=p.maxHp;p.mp=p.maxMp;p.alive=true;p.status={};});battle=null;mode='world';const r=REST[state.zone];state.player.x=r.x;state.player.y=r.y+45;recoverPlayerPosition();resetTrail();encounterGrace=3;saveGame(false);}
function retryBattle(){const specs=battle.enemies.map(e=>({type:e.type,level:e.level})),reward=battle.reward;state.party.forEach(p=>{p.hp=p.maxHp;p.mp=p.maxMp;p.alive=true;p.status={};});battle=null;mode='world';startBattle(specs,reward);}
const oldFinish=finishBattle;
finishBattle=function(won,escaped){if(battle?.reward.practice){state.party.forEach((p,i)=>{const old=battle.practiceParty?.[i];if(old)Object.assign(p,old);});if(battle.practiceInventory)state.inventory={...battle.practiceInventory};}oldFinish(won,escaped);};
const startBattleWithIntents=startBattle;
startBattle=function(specs,reward={}){const party=JSON.parse(JSON.stringify(state.party)),inventory={...state.inventory};startBattleWithIntents(specs,reward);if(reward.practice){battle.practiceParty=party;battle.practiceInventory=inventory;}};
const oldBattleInput=battleInput;
battleInput=function(k){if(k==='e')k='enter';if(battle.phase==='victory'&&(k==='enter'||k===' ')){finishBattle(true,false);return;}if(battle.phase==='defeat'){if(k==='enter'||k===' ')retryBattle();if(k==='escape')retreat();return;}if(battle.phase==='input'&&(k==='6'||((k==='enter'||k===' ')&&battle.menuIndex===5))){if(battle.reward.boss){battle.message='This checkpoint must be cleared. Defend, heal, or break the boss.';sfx('error');return;}finishBattle(false,true);return;}oldBattleInput(k);};
const baseUpdateBattle=updateBattle;
updateBattle=function(dt){baseUpdateBattle(dt);if(battle?.phase==='message'&&battle.pending?.advanceAfterMessage){battle.autoTimer=(battle.autoTimer||0)+dt;if(battle.autoTimer>.55){battle.autoTimer=0;advancePlayer();}}else if(battle)battle.autoTimer=0;};
partyPos=function(p){return [{x:174,y:292},{x:122,y:420},{x:336,y:360},{x:505,y:430}][state.party.indexOf(p)]||{x:174,y:292};};
enemyPos=function(e){const n=battle.enemies.length,i=battle.enemies.indexOf(e);return (n===1?[{x:985,y:374}]:n===2?[{x:875,y:330},{x:1110,y:397}]:[{x:815,y:335},{x:1000,y:401},{x:1150,y:285}])[i]||{x:985,y:374};};
function useFieldItem(key,target){const item=ITEMS[key];if(!state.inventory[key])return notify('NO '+item.name.toUpperCase()+' LEFT');if(!target.alive&&!item.revive)return notify('USE A MEDKIT TO REVIVE THIS ALLY');if(item.heal&&target.hp===target.maxHp||item.mp&&target.mp===target.maxMp)return notify('ALREADY FULL');state.inventory[key]--;if(item.heal){target.hp=Math.min(target.maxHp,target.hp+item.heal);target.alive=target.hp>0;}if(item.mp)target.mp=Math.min(target.maxMp,target.mp+item.mp);sfx('heal');saveGame(false);}
function buyUpgrade(i){const p=state.party[i],tier=adv().upgrades[p.name]||0,cost=140+tier*120;if(tier>=2)return notify('TRAINING COMPLETE');if(state.cash<cost)return notify('NEED '+cost+' CASH');state.cash-=cost;adv().upgrades[p.name]=tier+1;p.maxHp+=30;p.hp=Math.min(p.maxHp,p.hp+30);p.maxMp+=12;p.mp=Math.min(p.maxMp,p.mp+12);p.atk+=i===0||i===1?7:3;p.mag+=i===2||i===3?7:3;notify(p.label+' TRAINING UPGRADED');saveGame(false);}
function modalInput(k){if(k==='escape'){modal=null;return;}const a=adv();if(modal.type==='upgrade'){if(['arrowup','w'].includes(k))modal.selection=(modal.selection+3)%4;if(['arrowdown','s'].includes(k))modal.selection=(modal.selection+1)%4;if(['enter','e',' '].includes(k))buyUpgrade(modal.selection);return;}if(modal.type==='archive'){if(['arrowleft','a','arrowup','w'].includes(k))modal.selection=(modal.selection+2)%3;if(['arrowright','d','arrowdown','s'].includes(k))modal.selection=(modal.selection+1)%3;if(['1','2','3'].includes(k)){modal.selection=+k-1;k='enter';}if(['enter','e',' '].includes(k)){if(a.catalog.length<3){notify('FIND ALL THREE CATALOG CARDS FIRST');return;}a.archiveCode.push(modal.selection);if(a.archiveCode.length===3){if(a.archiveCode.join()==='0,1,2'){a.archiveOpen=true;modal=null;notify('VAULT UNLOCKED · RECOVER THE RED LEDGER');saveGame(false);}else{a.archiveCode=[];notify('WRONG ORDER · INTAKE → TRANSFER → RELEASE');sfx('error');}}}return;}if(modal.type==='channel'){if(['arrowleft','a'].includes(k))modal.selection=(modal.selection+2)%3;if(['arrowright','d'].includes(k))modal.selection=(modal.selection+1)%3;if(['arrowup','w'].includes(k))a.channel[modal.selection]=(a.channel[modal.selection]+1)%5;if(['arrowdown','s'].includes(k))a.channel[modal.selection]=(a.channel[modal.selection]+4)%5;if(['enter','e',' '].includes(k)){if(a.channel.join()==='2,4,1'){a.channelOpen=true;modal=null;notify('RELAY RESTORED · CONTROL ROOM ACCESS OPEN');saveGame(false);}else{notify('SIGNAL MISMATCH · MATCH 2 / 4 / 1');sfx('error');}}}};
const originalHandle=handleInput;
handleInput=function(k){if(modal)return modalInput(k);if(overlay==='status'){if(['escape','i'].includes(k)){overlay=null;return;}if(['arrowup','w'].includes(k))supplyIndex=(supplyIndex+5)%6;if(['arrowdown','s'].includes(k))supplyIndex=(supplyIndex+1)%6;if(['arrowleft','a'].includes(k))allyIndex=(allyIndex+3)%4;if(['arrowright','d'].includes(k))allyIndex=(allyIndex+1)%4;if(['enter','e',' '].includes(k))useFieldItem(Object.keys(ITEMS)[supplyIndex],state.party[allyIndex]);return;}originalHandle(k);};
const originalUpdate=update;
update=function(dt){if(modal){totalTime+=dt;if(toast.time>0)toast.time-=dt;return;}originalUpdate(dt);};
/* ---------------- Presentation ---------------- */
function topLabel(kicker,title,sub=''){panelText(kicker,58,45,13,'#8da7bd');text(title,58,73,32,'#f3f1e9');if(sub)panelText(sub,58,118,15,'#b0bfd0');}
function modalFrame(title,sub=''){ctx.fillStyle='#050b17df';ctx.fillRect(0,0,W,H);box(34,26,1212,668,'#101b2d','#698099');topLabel('CAPITOL QUEST / COMPLETE RECORD',title,sub);uiButton('Esc · Close',1080,48,135,40,()=>{overlay=null;modal=null;});}
function drawHeadingBackdrop(){tileRect('paving',0,465,W,255,64);ctx.fillStyle='#14233d';ctx.fillRect(0,0,W,465);ctx.fillStyle='#25446a';ctx.fillRect(0,90,W,270);for(let x=700;x<1280;x+=85)drawLandmark('TREE',x,290,2);drawLandmark('CAPITOL',870,95,3);ctx.fillStyle='#0a142a77';ctx.fillRect(0,0,W,H);}
drawTitle=function(){drawHeadingBackdrop();box(50,48,705,624,'#0b172cf2','#506982');pill('A FOUR-HERO RPG',88,80,'#83b8d8');text('CAPITOL',88,142,64,'#f4f1e8');text('QUEST',88,204,86,'#f8ce76');text('THE COMPLETE RECORD',93,308,19,'#b5d0e5');wrapped('A stolen key. A falsified broadcast. Four unlikely allies with one chance to get the complete story on the record.',92,354,560,18,'#b3c3d7',3);const opts=getTitleOptions();opts.forEach((o,i)=>uiButton(o.label,90,465+i*56,580,47,()=>{titleSelection=i;o.run();},{active:i===titleSelection,disabled:o.disabled}));panelText('WASD / arrows · Enter select · mouse & touch supported',92,646,12,'#8ca1bb');['TRUMP','HEGSETH','LUTNICK','RFK'].forEach((n,i)=>{const x=820+(i%2)*235,y=385+Math.floor(i/2)*225;drawShadow(x,y,38);drawActorFrame(ACT.action[n][0],x,y,BATTLE_SCALE[n]*1.08);text(ROLES[n],x,y+25,12,ACCENTS[n],'center');});panelText('Original sprite set · v'+VERSION,1220,686,12,'#93a5bb','right');};
drawStoryBackdrop=drawHeadingBackdrop;
drawCutscene=function(){drawHeadingBackdrop();const p=cutscene.pages[cutscene.i];box(65,325,1150,325,'#0c172bef','#617a95');if(p.portrait){drawPortrait(p.portrait,95,365,140,174);pill(ROLES[p.portrait]||'PARTY',97,562,ACCENTS[p.portrait]||'#f8ce76');}const x=p.portrait?270:105;text(p.speaker,x,365,18,'#f8ce76');wrapped(p.text,x,414,p.portrait?880:1030,22,'#eef2f8',6);panelText(`${cutscene.i+1} / ${cutscene.pages.length}`,105,612,14,'#92a6be');uiButton('Continue →',1010,578,170,47,()=>handleInput('enter'));};
drawDialogue=function(){ctx.fillStyle='#050b1733';ctx.fillRect(0,0,W,H);box(38,370,1204,324,'#0c172bf7','#70849b');if(dialogue.portrait)drawPortrait(dialogue.portrait,65,405,130,162);const x=dialogue.portrait?225:74;text(dialogue.speaker,x,405,22,'#f8ce76');wrapped(dialogue.lines[dialogue.i],x,450,dialogue.portrait?950:1100,21,'#eef3fb',5);panelText(`${dialogue.i+1} / ${dialogue.lines.length}`,74,650,14,'#9bafc7');uiButton('Continue →',1030,628,175,45,()=>handleInput('enter'));};
function drawNavigator(){const ob=getObjective();if(!ob)return;let target=ob;if(ob.zone!==state.zone){const route=['MALL','GROUNDS','ROTUNDA','ARCHIVE','PRESS','HEARING'],here=route.indexOf(state.zone),dest=route.indexOf(ob.zone),next=route[here+(dest>here?1:-1)];const names={MALL:'toMall',GROUNDS:'toGrounds',ROTUNDA:'toRotunda',ARCHIVE:'toArchive',PRESS:'toPress',HEARING:'toHearing'};const exit=interactables().find(i=>i.id===names[next]);if(exit)target=exit;else return;}const sx=target.x-camera.x,sy=target.y-camera.y;if(sx>50&&sx<W-50&&sy>92&&sy<WORLD_VIEW_H-55){ctx.strokeStyle='#f8ce76';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(sx,sy+8,27,10,0,0,Math.PI*2);ctx.stroke();return;}const dx=sx-W/2,dy=sy-WORLD_VIEW_H/2,k=Math.min((W/2-40)/Math.max(1,Math.abs(dx)),(WORLD_VIEW_H/2-70)/Math.max(1,Math.abs(dy))),x=W/2+dx*k,y=WORLD_VIEW_H/2+dy*k;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(dy,dx));ctx.fillStyle='#f8ce76';ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(-9,-9);ctx.lineTo(-9,9);ctx.closePath();ctx.fill();ctx.restore();}
drawWorldHUD=function(){box(18,18,550,73,'#0b172bea','#4c6680');panelText(ROOM_NAMES[state.zone],34,31,12,'#8ab4cd');text(MAPS[state.zone].name,34,53,20,'#fff2d2');box(806,18,456,73,'#0b172bea','#4c6680');panelText('NEXT OBJECTIVE',824,29,11,'#8ab4cd');wrapped(getObjective()?.label||'Case complete · free exploration',824,49,418,14,'#f7dd9b',2);drawNavigator();box(0,WORLD_VIEW_H,W,H-WORLD_VIEW_H,'#0c172a','#52708a');state.party.forEach((p,i)=>{const x=18+i*249;box(x,565,237,100,'#142238',allyIndex===i&&overlay==='status'?ACCENTS[p.name]:'#34465b');drawPortrait(p.name,x+10,575,54,67);panelText(p.label,x+75,576,14,ACCENTS[p.name]);panelText('HP '+p.hp+' / '+p.maxHp,x+75,598,12,'#eaf1fc');bar(x+75,618,145,7,p.hp,p.maxHp,'#99d4af');panelText('MP '+p.mp+' / '+p.maxMp,x+75,636,12,'#a7cbef');});uiButton('I · Supplies',1030,566,232,44,()=>{overlay='status';});uiButton('Esc · Pause',1030,621,232,44,()=>{mode='pause';pauseSelection=0;});const ni=nearestInteraction();panelText(ni?'E · '+(ni.data.label||ni.data.name):'Shift · Sprint     M · Map     Q · Journal',24,685,14,ni?'#f8ce76':'#92a8c0');panelText('$'+state.cash+'  ·  USB '+state.evidence.usb+'/4',1000,685,14,'#f8ce76','right');if(ni)buttons.push({x:0,y:670,w:630,h:50,fn:()=>interact(),label:'Interact'});};
drawBattleBackground=function(){ctx.fillStyle='#34577c';ctx.fillRect(0,0,W,300);const sky=ctx.createLinearGradient(0,70,0,305);sky.addColorStop(0,'#365780');sky.addColorStop(1,'#9fbdca');ctx.fillStyle=sky;ctx.fillRect(0,0,W,305);for(let x=0;x<W;x+=78)drawLandmark('TREE',x,182,2);drawLandmark('CAPITOL',576,82,2);tileRect('paving',0,301,W,169,64);if(!['MALL','GROUNDS'].includes(state.zone)){tileRect('floor',0,70,W,400,64);tileRect('carpet',530,80,220,390,64);for(let x of [40,265,970,1195])drawImageRect(TILE.column,x,94,72,143);drawImageRect(A.interior.SEAL,594,100,90,88);ctx.fillStyle=state.zone==='PRESS'?'#13285355':'#36232322';ctx.fillRect(0,70,W,400);}const vignette=ctx.createLinearGradient(0,300,0,470);vignette.addColorStop(0,'#050c1500');vignette.addColorStop(1,'#050c1555');ctx.fillStyle=vignette;ctx.fillRect(0,300,W,170);};
drawBattleUnits=function(){state.party.forEach(p=>{const pos=partyPos(p),sc=BATTLE_SCALE[p.name];let x=pos.x,y=pos.y,meta=ACT.action[p.name][0];drawShadow(x,y,30,.25);if(battle.phase==='action'&&battle.action?.actor===p){const a=battle.action,t=clamp(a.t/a.duration,0,1),off=attackType(a)!=='none';const strike=t<.38?t/.38:t>.7?(1-t)/.3:1;if(off&&p.name==='TRUMP'&&(a.kind==='basic'||a.skill?.kind==='physical')){const target=a.target||a.targets?.[0],dest=target?enemyPos(target).x-100:x+72;const dash=t<.42?Math.sin(t/.42*Math.PI/2):t>.57?Math.cos(clamp((t-.57)/.4,0,1)*Math.PI/2):1;x=lerp(pos.x,dest,dash);}else if(off&&p.name==='TRUMP')x+=Math.sin(t*Math.PI)*40;else if(off)x+=Math.sin(t*Math.PI)*12;if(t>.17&&t<.85)meta=ACT.action[p.name][a.pose??0];}if(p.hitTimer)x+=Math.sin(totalTime*80)*5;drawActorFrame(meta,x,y,sc,false,p.alive?1:.28);if(p.guard)pill('GUARD',pos.x-32,pos.y-160,'#a3d6ff');if(battle.phase==='input'&&currentActor()===p){drawDiamond(pos.x,pos.y-157,ACCENTS[p.name],8);ctx.strokeStyle=ACCENTS[p.name];ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(pos.x,pos.y+3,38,10,0,0,Math.PI*2);ctx.stroke();}if(battle.phase==='target'&&battle.pending?.targetType==='ally'){const selected=battleTargets()[battle.targetIndex]===p;if(selected){ctx.strokeStyle='#95deb8';ctx.lineWidth=3;ctx.strokeRect(pos.x-48,pos.y-142,96,149);}if(battleTargets().includes(p))buttons.push({x:pos.x-65,y:pos.y-145,w:130,h:154,label:p.label,fn:()=>{battle.targetIndex=battleTargets().indexOf(p);confirmBattleTarget(p);}});}});
 battle.enemies.forEach(e=>{const pos=enemyPos(e),sc=e.boss?1.18:1.04;let x=pos.x;if(battle.phase==='enemyAction'&&battle.action?.actor===e&&!e.broken)x-=Math.sin(clamp(battle.action.t/battle.action.duration,0,1)*Math.PI)*48;if(e.hitTimer)x+=Math.sin(totalTime*80)*5;drawShadow(pos.x,pos.y,33,.26);drawEnemySprite(e.sprite,x,pos.y,sc,false,e.hp>0?1:.18);if(e.hp>0){box(pos.x-82,pos.y+9,164,46,'#0b172bdd','#43566e');panelText(e.name,pos.x,pos.y+15,13,'#f0f3fa','center');bar(pos.x-69,pos.y+36,138,7,e.hp,e.maxHp,'#e89080');const intent=e.broken?'BREAK · loses turn':e.intent?.label||'';const iy=pos.y-ACT.enemy[e.sprite].r[3]*sc-31;box(pos.x-100,iy,200,23,'#0b172bdf',e.broken?'#7fdaeb':e.intent?.kind==='sweep'?'#f8ce76':'#617a8e');panelText(intent,pos.x,iy+5,11,e.broken?'#7fdaeb':'#f3dfb4','center');if(battle.phase==='target'&&battle.pending?.targetType==='enemy'||battle.phase==='analyze'){const selected=aliveEnemies()[battle.targetIndex]===e;if(selected){ctx.strokeStyle='#f8ce76';ctx.lineWidth=3;ctx.strokeRect(pos.x-83,pos.y-143,166,198);}buttons.push({x:pos.x-85,y:pos.y-145,w:170,h:200,label:e.name,fn:()=>{battle.targetIndex=aliveEnemies().indexOf(e);battleInput('enter');}});}}});};
drawBattleEffects=function(){for(const fx of spriteFx){const frames=EXTRA[fx.kind];if(!frames)continue;const i=Math.min(frames.length-1,Math.floor(fx.t/fx.duration*frames.length)),r=frames[i],sc=1.6;ctx.globalAlpha=1-fx.t/fx.duration*.45;drawExtra(fx.kind,fx.x-r[2]*sc/2,fx.y-r[3]*sc/2,r[2]*sc,r[3]*sc,i);}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=clamp(f.life/.9,0,1);ctx.strokeStyle='#0b1526';ctx.lineWidth=4;ctx.font='700 19px "QuestMono", monospace';ctx.textAlign='center';ctx.strokeText(f.text,f.x,f.y);text(f.text,f.x,f.y,19,f.color,'center');}ctx.globalAlpha=1;};
drawBattleHUD=function(){box(15,12,1250,60,'#0b172bf2','#637c97');panelText('ROUND '+battle.round,34,26,12,'#f8ce76');wrapped(battle.message,145,25,1090,16,'#f1f3f8',2);box(0,470,W,250,'#0c172a','#52708a');panelText('PARTY',23,486,12,'#91aac3');panelText('ACTION',752,486,12,'#91aac3');state.party.forEach((p,i)=>{const x=18,y=509+i*47,active=currentActor()===p&&['input','skills','items','target','analyze'].includes(battle.phase);box(x,y,704,43,active?'#273348':'#132137',active?ACCENTS[p.name]:'#283b52');drawPortrait(p.name,x+5,y+4,28,35);panelText(p.label,x+43,y+6,14,p.alive?ACCENTS[p.name]:'#7b8899');panelText('HP '+p.hp+'/'+p.maxHp,x+175,y+5,12,'#e1edfa');bar(x+175,y+25,148,6,p.hp,p.maxHp,'#96d5aa');panelText('MP '+p.mp+'/'+p.maxMp,x+345,y+5,12,'#abc9eb');bar(x+345,y+25,120,6,p.mp,p.maxMp,'#8dc6ff');panelText(p.limit>=100?'LIMIT READY':'LIMIT '+p.limit+'%',x+490,y+5,12,p.limit>=100?'#f0a7de':'#bbaacb');bar(x+490,y+25,115,6,p.limit,100,'#d99fd9');const st=statusText(p);if(st)panelText(st,x+626,y+14,10,'#adccee');});drawBattleMenuPanel();};
// Command panels share a fixed grid. All six supplies are visible and selectable.
drawBattleMenuPanel=function(){const p=currentActor(),phase=battle.phase,x=748;
 if(phase==='input'||phase==='intro'){const cmds=[BASIC_NAMES[p.name],'Skills','Items','Defend','Analyze','Disengage'];cmds.forEach((s,i)=>uiButton(`${i+1} · ${s}`,x+(i%2)*256,510+Math.floor(i/2)*53,244,44,()=>{battle.menuIndex=i;battleInput('enter');},{active:phase==='input'&&battle.menuIndex===i,disabled:phase==='intro'||i===5&&!!battle.reward.boss}));panelText('Weakness × 2 = BREAK · Skills build LIMIT',x,683,12,'#9cafc7');}
 else if(phase==='skills'){const list=skillsFor(p);list.forEach((s,i)=>uiButton(s.name,x+(i%2)*256,510+Math.floor(i/2)*68,244,60,()=>{battle.subIndex=i;chooseSkill(s);},{active:battle.subIndex===i,disabled:!s.limit&&p.mp<s.cost,sub:s.limit?'LIMIT · Ready':s.cost+' MP · '+s.target,accent:ACCENTS[p.name]}));wrapped(list[battle.subIndex]?.desc||'',x,655,488,14,'#b9c9dd',2);}
 else if(phase==='items'){battleItems().forEach(([k,v],i)=>uiButton(ITEMS[k].name+' ×'+v,x+(i%2)*256,510+Math.floor(i/2)*53,244,44,()=>{battle.subIndex=i;chooseItem(k);},{active:battle.subIndex===i}));panelText(ITEMS[battleItems()[battle.subIndex]?.[0]]?.desc||'',x,683,13,'#b9c9dd');}
 else if(phase==='target'){const ts=battleTargets(),t=ts[battle.targetIndex];text('SELECT '+(battle.pending.targetType==='enemy'?'ENEMY':'ALLY'),x,517,21,'#f8ce76');panelText(t?.label||t?.name||'',x,554,19,'#f3f4f7');if(battle.pending.targetType==='enemy'&&t)panelText('Weak: '+weakness(t).toUpperCase()+(t.resolveTurns?' · RESOLVE: break immune':' · Break '+(t.breakPoints||0)+'/2'),x,585,14,'#90d5e9');else if(t)panelText('HP '+t.hp+'/'+t.maxHp+' · MP '+t.mp+'/'+t.maxMp,x,585,14,'#96d5aa');uiButton('← Previous',x,620,152,44,()=>battleInput('arrowleft'));uiButton('Confirm',x+162,620,164,44,()=>battleInput('enter'),{active:true});uiButton('Next →',x+336,620,152,44,()=>battleInput('arrowright'));panelText('Click a character to confirm · Esc cancel',x,683,12,'#9cafc7');}
 else if(phase==='analyze'){const e=aliveEnemies()[battle.targetIndex];text('ANALYZE · '+e.name,x,517,20,'#f8ce76');panelText(e.trait,x,552,15,'#bcd1e7');panelText('Weak: '+weakness(e).toUpperCase(),x,580,15,'#90d5e9');wrapped('Mark vulnerable for two rounds. Uses this hero’s action.',x,609,480,14,'#b9c9dd',2);uiButton('Analyze',x,657,488,42,()=>battleInput('enter'),{active:true});}
 else if(phase==='victory'){text('ENCOUNTER CLEARED',x,518,23,'#f8ce76');panelText('+'+(battle.result?.gold||0)+' CASH     +'+(battle.result?.xp||0)+' XP',x,561,18,'#e9edf3');wrapped('Party recovers 12% HP and 10% MP after victory.',x,592,488,14,'#b9c9dd',2);uiButton('Continue →',x,650,488,49,()=>battleInput('enter'),{active:true});}
 else if(phase==='defeat'){text('REGROUP',x,518,24,'#efac9b');wrapped('Keep your progress. Retry at full strength or return to this area’s rest point.',x,562,488,16,'#b9c9dd',3);uiButton('Retry',x,650,235,49,retryBattle,{active:true});uiButton('Recover',x+253,650,235,49,retreat);}
 else {text(phase==='enemyAction'?'ENEMY TURN':phase==='message'?'RESOLVED':'IN MOTION',x,531,22,phase==='enemyAction'?'#efac9b':'#f8ce76');wrapped(battle.message,x,578,480,16,'#b9c9dd',4);if(phase==='message'&&!battle.pending?.advanceAfterMessage)uiButton('Continue',x,658,488,41,()=>battleInput('enter'));}
};
drawStatusOverlay=function(){modalFrame('PARTY & SUPPLIES','Select an ally, select a supply, then use it. Medkits also revive fallen allies.');state.party.forEach((p,i)=>{const x=58+i*294;box(x,170,282,225,allyIndex===i?'#243149':'#132138',allyIndex===i?ACCENTS[p.name]:'#344b65');drawPortrait(p.name,x+16,188,73,91);text(p.label,x+103,191,17,ACCENTS[p.name]);panelText('LV '+p.lvl+' · '+ROLES[p.name],x+103,220,11,'#a5bad0');panelText('HP '+p.hp+'/'+p.maxHp,x+16,295,15,'#e2edf9');bar(x+16,319,245,7,p.hp,p.maxHp,'#95deb8');panelText('MP '+p.mp+'/'+p.maxMp,x+16,337,14,'#accbef');bar(x+16,362,245,7,p.mp,p.maxMp,'#8cc5ff');buttons.push({x,y:170,w:282,h:225,label:p.label,fn:()=>{allyIndex=i;}});});Object.keys(ITEMS).forEach((k,i)=>{const x=58+i%3*392,y=422+Math.floor(i/3)*83;uiButton(ITEMS[k].name+' ×'+(state.inventory[k]||0),x,y,376,71,()=>{supplyIndex=i;},{active:supplyIndex===i,sub:ITEMS[k].desc});});uiButton('Use '+ITEMS[Object.keys(ITEMS)[supplyIndex]].name+' → '+state.party[allyIndex].label,58,610,768,55,()=>useFieldItem(Object.keys(ITEMS)[supplyIndex],state.party[allyIndex]),{active:true});panelText('↑↓ item · ←→ ally · Enter use',858,630,13,'#a9bdd3');};
drawShop=function(){modalFrame('QUARTERMASTER','$'+state.cash+' available · Supplies for the road and the next encounter.');buttons[buttons.length-1].fn=()=>{mode='world';shop=null;};Object.keys(ITEMS).forEach((k,i)=>{const x=58+i%2*588,y=176+Math.floor(i/2)*145;const it=ITEMS[k];box(x,y,570,127,'#142238','#344b65');drawItem(k,x+42,y+48,43);text(it.name,x+84,y+20,20,'#f4e7c6');panelText(it.desc,x+84,y+52,15,'#aabed4');uiButton('Buy · $'+it.price,x+345,y+75,204,37,()=>{shop.selected=i;shopInput('enter');},{active:shop.selected===i,disabled:state.cash<it.price});panelText('In bag: '+(state.inventory[k]||0),x+21,y+91,13,'#94abc4');});};
drawPause=function(){ctx.fillStyle='#050b17c9';ctx.fillRect(0,0,W,H);box(380,34,520,654,'#0d1a2f','#657e98');text('PAUSED',420,74,31,'#f5e6c1');panelText(MAPS[state.zone].name,420,122,14,'#8eabc5');pauseOptions().forEach((o,i)=>uiButton(o.label,415,172+i*65,450,54,()=>{pauseSelection=i;o.run();},{active:pauseSelection===i}));};
drawQuestOverlay=function(){modalFrame('CASE JOURNAL','The record, the route, and what remains.');const q=MAIN_STAGES[state.mainStage];box(58,168,715,157,'#1c2c43','#688199');pill('CHAPTER '+state.chapter,78,184,'#95bedc');text(q.title,78,222,26,'#f8ce76');wrapped(getObjective()?.label||q.desc,78,266,660,17,'#c3d2e4',2);text('EVIDENCE CHAIN',822,178,16,'#8fbedc');[['Relay key',state.flags.megaphone],['Red Ledger',state.flags.ledger],['Source transcript',state.flags.transcript],['Verification',state.flags.factChecked],['Public record',state.flags.ending]].forEach(([s,done],i)=>{panelText(done?'✓':'○',828,220+i*47,19,done?'#95deb8':'#617892');panelText(s,860,222+i*47,17,done?'#e5eef7':'#9badc2');});text('RECENT PROGRESS',58,358,15,'#8fbedc');state.log.slice(0,5).forEach((l,i)=>wrapped(l.text,58,393+i*45,710,14,'#aebfd4',2));const voices=Object.values(state.witnesses).filter(Boolean).length;panelText('Five voices: '+Math.min(5,voices)+'/5',825,503,16,'#f8ce76');panelText('Clean backups: '+state.evidence.usb+'/4',825,539,16,'#94cce7');panelText('Supply caches: '+Object.keys(adv().chests).length+'/6',825,575,16,'#95deb8');};
drawMapOverlay=function(){modalFrame('DISTRICT MAP','Gold: objective · Cyan: people · Red: encounters · Green: rest · White: you');const bx=58,by=170,bw=790,bh=450,m=currentMap(),sc=Math.min(bw/m.w,bh/m.h),ox=bx+(bw-m.w*sc)/2,oy=by+(bh-m.h*sc)/2;box(bx,by,bw,bh,'#182c3d','#4c6980');ctx.fillStyle='#68768a';worldSolids(state.zone).forEach(r=>ctx.fillRect(ox+r.x*sc,oy+r.y*sc,r.w*sc,r.h*sc));const dot=(p,c,r=4)=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(ox+p.x*sc,oy+p.y*sc,r,0,Math.PI*2);ctx.fill();};npcList().forEach(n=>dot(n,'#90d9e8'));(WORLD_ENCOUNTERS[state.zone]||[]).filter(m=>!state.defeated[mobKey(state.zone,m.id)]).forEach(m=>dot(m,'#f4978d'));interactables().filter(i=>!i.hidden?.()).forEach(i=>dot(i,'#c9cbb8',3));dot(REST[state.zone],'#95deb8',6);const ob=getObjective();if(ob?.zone===state.zone)dot(ob,'#f8ce76',9);dot(state.player,'#ffffff',7);['MALL','GROUNDS','ROTUNDA','ARCHIVE','PRESS','HEARING'].forEach((z,i)=>{const y=175+i*65;box(880,y,328,55,z===state.zone?'#293b50':'#142238',z===state.zone?'#f8ce76':'#344b65');panelText((i+1).toString().padStart(2,'0'),897,y+17,16,'#7295b2');panelText(MAPS[z].name,937,y+18,14,adv().visited[z]?'#eaf0f8':'#7d8fa6');});wrapped(ob?.label||'Case closed · explore freely.',883,586,309,14,'#f8ce76',3);};
function drawModal(){const a=adv();if(modal.type==='upgrade'){modalFrame('PARTY TRAINING','$'+state.cash+' available · Permanent upgrades: +30 HP, +12 MP, and stronger attacks.');state.party.forEach((p,i)=>{const tier=a.upgrades[p.name]||0,cost=140+tier*120;drawPortrait(p.name,66,176+i*116,66,83);uiButton(p.label+' · '+ROLES[p.name],154,176+i*116,1052,98,()=>{modal.selection=i;buyUpgrade(i);},{active:modal.selection===i,disabled:tier>=2||state.cash<cost,sub:tier>=2?'Fully trained':`Tier ${tier+1}/2 · $${cost} · +7 ${i<2?'ATK':'MAG'}, +3 ${i<2?'MAG':'ATK'}`});});}
 else if(modal.type==='archive'){modalFrame('THE LEDGER VAULT','A document moves through intake, transfer, and release. Enter those catalog stamps in order.');CATALOG.forEach((c,i)=>{const x=64+i*394;box(x,183,378,179,'#172840','#47637f');pill('CATALOG '+(i+1),x+21,204,'#91bddb');text(a.catalog.includes(i)?c.label:'CARD MISSING',x+22,250,23,a.catalog.includes(i)?'#f8ce76':'#758ba2');panelText(a.catalog.includes(i)?'Recovered from the stacks':'Find the marked shelf',x+22,300,15,'#aabed4');});panelText('STAMP SEQUENCE',64,402,14,'#91bddb');text(a.archiveCode.map(i=>['04','17','29'][i]).concat(Array(3-a.archiveCode.length).fill('__')).join('  →  '),64,440,34,'#f4e5bd');[0,1,2].forEach((v,i)=>uiButton(['1 · 04 / Intake','2 · 17 / Transfer','3 · 29 / Release'][i],64+i*394,521,378,64,()=>{modal.selection=i;modalInput('enter');},{active:modal.selection===i,disabled:a.catalog.length<3}));panelText('Choose three stamps · Wrong sequences reset without a penalty',64,628,15,'#aabed4');}
 else if(modal.type==='channel'){modalFrame('RELAY TUNER','The maintenance card reads 2 / 4 / 1. Match all three channels, then reconnect.');for(let i=0;i<3;i++){const x=130+i*350;box(x,184,310,335,'#15273e',modal.selection===i?'#f8ce76':'#47637f');panelText(['CARRIER','PHASE','GAIN'][i],x+155,210,16,'#a5c4dd','center');uiButton('▲',x+40,253,230,47,()=>{modal.selection=i;modalInput('arrowup');},{active:modal.selection===i});text(a.channel[i],x+155,319,82,'#f8ce76','center');uiButton('▼',x+40,438,230,47,()=>{modal.selection=i;modalInput('arrowdown');});}uiButton('Reconnect relay',130,560,1010,65,()=>modalInput('enter'),{active:true});panelText('←→ choose channel · ↑↓ tune · Enter reconnect',130,646,15,'#aabed4');}}
drawToast=function(){const alpha=clamp(toast.time/.25,0,1);ctx.save();ctx.globalAlpha=alpha;const w=Math.min(1060,Math.max(400,toast.text.length*9+36)),x=(W-w)/2;box(x,102,w,52,'#10253cf5','#8099ae');wrapped(toast.text,x+18,114,w-36,15,'#f4e5bd',2);ctx.restore();};
drawEnding=function(){drawHeadingBackdrop();box(45,40,1190,640,'#0c172bf5','#698198');topLabel('THE COMPLETE RECORD','The final decision');if(ending.step==='choice'){wrapped('The source trail is verified. The hearing is over. Decide how the complete record reaches the public.',58,170,1130,24,'#d5e1ee',3);[['BROADCAST NOW','Release the complete source package immediately, with the corrections attached.'],['FILE WITH THE HEARING','Enter the package into the hearing record before the public relay opens.']].forEach((o,i)=>uiButton((i+1)+' · '+o[0],60,340+i*124,1158,104,()=>{ending.choice=i;endingInput('enter');},{active:ending.choice===i,sub:o[1]}));}else{wrapped(endingPages()[ending.page],60,210,1120,27,'#eef2f8',7);panelText('Evidence USBs '+state.evidence.usb+'/4 · Witnesses '+Object.values(state.witnesses).filter(Boolean).length+' · Encounters won '+adv().battles,60,543,16,'#95bedb');uiButton('Continue →',875,597,327,53,()=>endingInput('enter'),{active:true});}};
const baseDraw=draw;
draw=function(){buttons=[];baseDraw();if(modal){buttons=[];drawModal();if(toast.time>0)drawToast();}const visibleLabels=buttons.filter(b=>!b.disabled).map(b=>b.label).join(', ');canvas.setAttribute('aria-label',mode==='battle'?`Battle round ${battle.round}. ${battle.message}. ${visibleLabels}`:`${mode}. ${getObjective()?.label||'Capitol Quest'}. ${visibleLabels}`);canvas.style.cursor=buttons.some(b=>!b.disabled&&pointer.x>=b.x&&pointer.x<b.x+b.w&&pointer.y>=b.y&&pointer.y<b.y+b.h)?'pointer':'default';};
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*W/r.width;pointer.y=(e.clientY-r.top)*H/r.height;});
canvas.addEventListener('pointerleave',()=>{pointer.x=-1;pointer.y=-1;});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;const b=[...buttons].reverse().find(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h);if(b&&!b.disabled){initAudio();b.fn();sfx('confirm');}});
window.addEventListener('keydown',e=>{if(e.key==='Shift')e.preventDefault();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(mode==='world'&&!overlay&&!modal){pauseSelection=0;mode='pause';}}});
// Stable debug access used by the bundled regression checks.
Object.assign(window.__CQ__,{startBattle:(...args)=>startBattle(...args),getObjective:()=>getObjective(),interactables:()=>interactables(),draw:()=>draw(),update:dt=>update(dt),worldSolids:z=>worldSolids(z),freshState:()=>freshState(),startNewGame:()=>startNewGame(),getModal:()=>modal,getButtons:()=>buttons,clearModal:()=>modal=null,recoverPlayerPosition,collides,REST,BREAKERS,CATALOG,partyPos,enemyPos,recordTrail,followerAt,battleTargets,weakness,finishBattle,winBattle,loseBattle,retreat,retryBattle,resolvePlayerAction,resolveEnemyAction,refreshIntents,skillsFor,chooseSkill,chooseItem,confirmBattleTarget,useFieldItem,buyUpgrade,keys,resetTrail,beginPlayerAction,advancePlayer,tickStatuses,updateWorld,startEnemyPhase,saveGame,loadGame});
const battleBackdrop=new Image();battleBackdrop.src='assets/battle_backdrop.png';
const tiledBattleBackground=drawBattleBackground;
drawBattleBackground=function(){if(['MALL','GROUNDS'].includes(state.zone)&&battleBackdrop.width){ctx.drawImage(battleBackdrop,0,0,1536,740,0,0,W,BATTLE_VIEW_H);ctx.fillStyle='#11254126';ctx.fillRect(0,0,W,BATTLE_VIEW_H);}else tiledBattleBackground();};
drawHeadingBackdrop=function(){if(battleBackdrop.width){ctx.drawImage(battleBackdrop,0,0,W,H);ctx.fillStyle='#07142677';ctx.fillRect(0,0,W,H);}else {ctx.fillStyle='#172c43';ctx.fillRect(0,0,W,H);}};
drawStoryBackdrop=drawHeadingBackdrop;
bar=function(x,y,w,h,value,max,color='#95deb8'){ctx.fillStyle='#334259';ctx.fillRect(x,y,w,h);const frac=clamp(max?value/max:0,0,1);ctx.fillStyle=color;ctx.fillRect(x,y,Math.round(w*frac),h);};
resetTrail=function(){const p=state.player;trail=[{x:p.x,y:p.y,dir:p.dir,frame:0}];const v=p.dir==='up'?{x:0,y:1}:p.dir==='down'?{x:0,y:-1}:p.dir==='left'?{x:1,y:0}:{x:-1,y:0};for(let i=1;i<=75;i++){const x=p.x+v.x*i*2,y=p.y+v.y*i*2;if(collides(x,y))break;trail.push({x,y,dir:p.dir,frame:0});}lastTrailPoint={...trail[0]};trailDistance=0;};
// Exploration landmarks, scenery and NPCs always use original assets.
WORLD_ENCOUNTERS.ARCHIVE[0].x=760;WORLD_ENCOUNTERS.ARCHIVE[0].y=870;
// Resolve any impossible legacy spawn on load before movement resumes.
recoverPlayerPosition();resetTrail();
Object.assign(window.__CQ__,{resetTrail:()=>resetTrail(),draw:()=>draw()});
const propsAtlas=new Image();propsAtlas.src='assets/props.png';
function drawProp(key,x,y,w,h){const r=PROPS[key];if(!r||!propsAtlas.width)return;const sc=Math.min(w/r[2],h/r[3]),dw=Math.round(r[2]*sc),dh=Math.round(r[3]*sc);ctx.drawImage(propsAtlas,...r,Math.round(x+(w-dw)/2),Math.round(y+h-dh),dw,dh);}
const rawDrawImageRect=drawImageRect;
drawImageRect=function(r,x,y,w,h,alpha=1){const key=Object.keys(A.interior).find(k=>A.interior[k]===r);if(key&&PROPS[key]){ctx.save();ctx.globalAlpha=alpha;drawProp(key,x,y,w,h);ctx.restore();return;}rawDrawImageRect(r,x,y,w,h,alpha);};
TILE.floor=[1326,96,30,30];
TILE.paving=[1326,53,34,31];
TILE.shelf=[1477,436,44,43];
drawColumn=function(x,y){drawProp('COLUMN',x,y,75,163);};
drawDesk=function(x,y,w,h){box(x,y,w,h,'#79523e','#3b2b28');for(let xx=x+4;xx<x+w-80;xx+=100)drawProp('DESK',xx,y,100,h);};
drawReadingTable=function(x,y){box(x,y,510,115,'#76503a','#3a2825');ctx.fillStyle='#b28a5a';ctx.fillRect(x+10,y+7,490,8);for(let i=0;i<5;i++)drawItem('DOC',x+55+i*100,y+50,26);};
// Messages stay in a dedicated footer on menus, away from titles and controls.
const mainToast=drawToast;
drawToast=function(){if(overlay||modal||mode==='shop'||mode==='pause'){ctx.save();ctx.globalAlpha=clamp(toast.time/.25,0,1);box(350,674,580,36,'#192b41','#7890a6');panelText(toast.text,640,684,12,'#f4e5bd','center');ctx.restore();}else mainToast();};
const mainBattleEffects=drawBattleEffects;
drawBattleEffects=function(){const a=battle.action;if(battle.phase==='action'&&a?.actor&&a.t>.12&&a.t<.36&&attackType(a)!=='none'&&a.actor.name!=='TRUMP'){const targets=(a.target?[a.target]:a.targets||[]).filter(e=>battle.enemies.includes(e));for(const target of targets){const from=partyPos(a.actor),to=enemyPos(target),t=clamp((a.t-.12)/.24,0,1),key=a.actor.name==='HEGSETH'?'gun':a.actor.name==='LUTNICK'?'money':'heal',frame=a.actor.name==='HEGSETH'?1:2;const r=EXTRA[key][frame];drawExtra(key,lerp(from.x+35,to.x,t)-r[2]/2,lerp(from.y-72,to.y-64,t)-r[3]/2,r[2]*1.3,r[3]*1.3,frame);}}mainBattleEffects();};
// Small original chiptune score. Synthesized locally; no external audio or network dependency.
let musicBeat=0,musicClock=0,musicScene='';
function musicNote(midi,duration,gain=.012,type='triangle'){if(!audioCtx||audioCtx.state!=='running')return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type=type;o.frequency.value=440*Math.pow(2,(midi-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+duration+.02);}
function updateMusic(dt){if(!state.settings.sound||!audioCtx||mode==='pause')return;const scene=mode==='battle'?'battle':'world';if(scene!==musicScene){musicScene=scene;musicBeat=0;musicClock=0;}musicClock-=dt;if(musicClock>0)return;const tempo=scene==='battle'?.19:.34;musicClock=tempo;const roots=scene==='battle'?[45,45,41,43]:[48,43,45,41],root=roots[Math.floor(musicBeat/16)%4],melody=scene==='battle'?[0,7,12,10,7,3,7,12]:[0,7,12,7,3,10,7,3];musicNote(root+12+melody[musicBeat%8],tempo*.85,scene==='battle'?.011:.008,'triangle');if(musicBeat%4===0)musicNote(root,tempo*3.8,.014,'triangle');if(scene==='battle'&&musicBeat%2===0)musicNote(30,tempo*.23,.008,'square');musicBeat++;}
const gameUpdateWithModal=update;
update=function(dt){gameUpdateWithModal(dt);if(!modal&&!overlay)updateMusic(dt);};
drawControlsOverlay=function(){modalFrame('HOW TO PLAY','Six connected areas. Three bosses. One complete record.');const lines=[['MOVE','WASD / arrows. Hold Shift to sprint.'],['INTERACT','E / Enter near a person, marker or item.'],['MENUS','Click / tap buttons, or arrows + Enter. Esc goes back.'],['EXPLORE','M opens the map. Q opens the case journal.'],['RECOVER','I opens supplies. Medkits revive. Green rest points fully heal.'],['COMBAT','Each living hero acts once, then enemies respond.'],['WEAKNESSES','Physical / hybrid / magic. Two weakness hits cause BREAK.'],['ENEMY TELLS','Read the intent above each enemy. Defend against charged hits.'],['PROGRESSION','Win XP, find caches, buy supplies or upgrade at the Mall.'],['SAVING','Rest points, story milestones, F5 and periodic autosave.']];lines.forEach(([k,v],i)=>{const y=180+i*43;panelText(k,65,y,14,'#f8ce76');panelText(v,230,y,15,'#becfe2');});panelText('Sound and screen shake can be toggled in Pause. This game is fictional satire.',65,634,13,'#8ba4bd');};
const originalTitleOptions=getTitleOptions;
getTitleOptions=function(){const opts=originalTitleOptions(),newGame=opts[0];newGame.run=()=>{if(storageGet(SAVE_KEY)){modal={type:'newgame',selection:0};}else startNewGame();};return opts;};
const standardModalInput=modalInput;
modalInput=function(k){if(modal?.type==='newgame'){if(k==='escape'){modal=null;return;}if(['arrowleft','arrowright','a','d'].includes(k))modal.selection=1-modal.selection;if(k==='enter'||k===' '){if(modal.selection===1){modal=null;startNewGame();}else modal=null;}return;}standardModalInput(k);};
const standardModalDraw=drawModal;
drawModal=function(){if(modal.type==='newgame'){modalFrame('START A NEW GAME?','Your current autosave will be replaced once the new introduction ends.');wrapped('You can continue your existing adventure from the title screen. Your earlier save slot stays untouched.',64,235,1120,23,'#cedbe9',4);uiButton('Keep current game',64,470,548,70,()=>{modal=null;},{active:modal.selection===0});uiButton('Begin new game',642,470,548,70,()=>{modal=null;startNewGame();},{active:modal.selection===1});return;}standardModalDraw();};
// Export/import keeps saves portable when the standalone game is moved to another folder.
function exportSave(){const payload=JSON.stringify({version:VERSION,state},null,2),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([payload],{type:'application/json'}));link.download='Capitol_Quest_Save.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);notify('SAVE EXPORTED');}
function importSaveFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.state||!Array.isArray(data.state.party)||!data.state.player||!MAPS[data.state.zone])throw Error('invalid');const clean=freshState();mergeState(clean,data.state);if(clean.party.some(p=>!PARTY_DEFS[p.name]||![p.hp,p.mp,p.maxHp,p.maxMp,p.atk,p.def,p.mag].every(Number.isFinite)))throw Error('invalid');storageSet(SAVE_KEY,JSON.stringify({version:VERSION,state:clean}));modal=null;loadGame();}catch(e){notify('SAVE FILE COULD NOT BE READ');}};reader.readAsText(file);}
Object.assign(window.__CQ__,{update:dt=>update(dt),input:k=>handleInput(k)});
const loadedDraw=draw;
const gameImages=[atlas,actorAtlas,landmarkAtlas,extraAtlas,propsAtlas,battleBackdrop];
let assetError=false;gameImages.forEach(im=>{im.onerror=()=>{assetError=true;};});
draw=function(){const ready=gameImages.filter(im=>im.width>0).length;if(ready<gameImages.length){buttons=[];ctx.fillStyle='#0c172a';ctx.fillRect(0,0,W,H);text('CAPITOL QUEST',W/2,265,40,'#f8ce76','center');panelText(assetError?'An artwork file is missing. Keep the assets folder beside index.html.':'Loading the original artwork…',W/2,335,17,'#a5bdd3','center');bar(400,393,480,7,ready,gameImages.length);return;}loadedDraw();};
Object.assign(window.__CQ__,{draw:()=>draw()});
// Reuse tile patterns so large maps do not redraw thousands of individual tiles every frame.
const tilePatterns=new Map();
tileRect=function(key,x,y,w,h,size=64){const r=TILE[key];if(!atlasReady||!r)return;const cacheKey=key+':'+r.join(',')+':'+size;let pattern=tilePatterns.get(cacheKey);if(!pattern){const tile=document.createElement('canvas');tile.width=size;tile.height=size;const tc=tile.getContext('2d');tc.imageSmoothingEnabled=false;tc.drawImage(atlas,...r,0,0,size,size);pattern=ctx.createPattern(tile,'repeat');tilePatterns.set(cacheKey,pattern);}ctx.save();ctx.translate(x,y);ctx.fillStyle=pattern;ctx.fillRect(0,0,w,h);ctx.restore();};
let touchMenuSignature='';
function syncTouchMenu(){const host=document.getElementById('touchMenu');if(!host?.replaceChildren)return;const signature=buttons.map(b=>b.label+!!b.disabled).join('|');if(signature===touchMenuSignature)return;touchMenuSignature=signature;host.replaceChildren(...buttons.map((b,i)=>{const el=document.createElement('button');el.textContent=b.label;el.disabled=!!b.disabled;el.onclick=()=>{initAudio();buttons[i]?.fn?.();};return el;}));}
const finalDraw=draw;
draw=function(){finalDraw();syncTouchMenu();};
Object.assign(window.__CQ__,{draw:()=>draw()});
