function installDebugTools() {
  window.__CQ__ = {
    state,
    A,
    ACT,
    BG,
    LAND,
    EXTRA,
    PROPS,
    MAPS,
    WORLD_ENCOUNTERS,
    PARTY_DEFS,
    ENEMY_DEFS,
    DISTRICTS,
    SIDE_MISSIONS,
    LINKS,
    LOCATIONS,
    TRIALS,
    SKILL_LEVELS,
    WALK_FRAMES,
    ENEMY_FACING,
    findPath,
    npcList,
    sceneryEntities,
    districtScene,
    drawMapBase,
    drawWorldEntities,
    drawMapObjects,
    sceneryFrame,
    fieldObjectType,
    worldFocus,
    worldFocusLabel,
    updateMobs,
    getMobMotion: () => worldMobMotion,
    drawActorFrame,
    partyPos,
    battlePartyPose,
    startDialogue,
    endingPages,
    get dialogue() {
      return dialogue;
    },
    xpRequired,
    grantPartyXP,
    buyTalent,
    chooseAutoAction,
    beginTrial,
    setAutoMode,
    getObjective,
    interactables,
    worldSolids,
    startNewGame,
    freshState,
    startBattle,
    zoneTransition,
    finishBattle,
    winBattle,
    retreat,
    retryBattle,
    resolvePlayerAction,
    resolveEnemyAction,
    skillsFor,
    chooseSkill,
    battleTargets,
    saveGame,
    loadGame,
    draw,
    update,
    sideState,
    makeEnemy,
    refreshIntents,
    restoreParty,
    mergeState,
    resetTrail,
    setStage,
    VERSION,
    input: handleInput,
    getBattle: () => battle,
    getOverlay: () => overlay,
    setModal: (m) => (modal = m),
    setOverlay: (o) => (overlay = o),
    get mode() {
      return mode;
    },
    setMode: (v) => (mode = v),
  };
}
