import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "esbuild";
import { buildSpriteMasks } from "./build-sprite-masks.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sources = JSON.parse(
  await readFile(resolve(root, "scripts/sources.json"), "utf8"),
);
const masks = await buildSpriteMasks();
const manifests = await Promise.all(
  ["actors", "landmarks"].map(async (name) =>
    JSON.parse(
      await readFile(resolve(root, `assets/${name}_manifest.json`), "utf8"),
    ),
  ),
);
const manifestSource = `const ACT=${JSON.stringify(manifests[0])};const LAND=${JSON.stringify(manifests[1])};const SPRITE_MASKS=${JSON.stringify(masks)};`;
const parts = await Promise.all(
  sources.map(
    async (file) =>
      `// ${file}\n${await readFile(resolve(root, file), "utf8")}`,
  ),
);
// Components share one private lexical scope. The source list controls initialization;
// browsers receive one script, with no load-order patches or module server requirement.
const result = await transform(
  `(() => {\n'use strict';\n${manifestSource}\n${parts.join("\n\n")}\n})();`,
  {
    loader: "js",
    target: "es2022",
    minify: false,
    legalComments: "none",
    banner: "// Generated by npm run build. Edit src/; do not edit this file.",
  },
);
await mkdir(resolve(root, "dist"), { recursive: true });
await writeFile(resolve(root, "dist/game.js"), result.code);
console.log(`Built ${sources.length} source components → dist/game.js`);
